### ISSUE TITLE
Format selection script.fsx, cursor goes to end of file

### ISSUE THREAD

**Issue by philderbeast** [fsprojects/VisualFSharpPowerTools#967] opened 2015-05-18 19:44 UTC
Moved from https://github.com/Microsoft/visualfsharp/issues/455

In Visual Studio 2015 CTP, open an fsharp *.fsx script file and choose Edit|Advanced|Format Selection. If the code is reformatted then the cursor jumps to the end of the file after the reformatting. I would have expected the cursor to stay on the same line.

I tested this with the banana pyjamas loop in the following file at rev d3d937ed12c8d091f984870a9b7ee3c4295cbee4 ...

https://github.com/BlockScope/ExpertFSharp/blob/master/04Imperative/Script.fsx

**Comment by dungpa** [comment] 2015-06-23 20:36
I can't reproduce the issue. If you can give me a screenshot of which code block you selected, it would be great.

By the way, the script at https://github.com/BlockScope/ExpertFSharp/blob/d3d937ed12c8d091f984870a9b7ee3c4295cbee4/04Imperative/Script.fsx consists of many errors because it is copied/pasted from F# Interactive. Most of the time, formatting will fail for such programs.

**Comment by dungpa** [comment] 2015-07-14 18:54
Closing. Feel free to open another issue if you find a repro.

**Closed by dungpa** 2015-07-14 18:54 UTC
Labels: minor bug, no-repro

**Comment by philderbeast** [comment] 2015-08-03 12:54
The line range for the loop is ...

https://github.com/BlockScope/ExpertFSharp/blob/d3d937ed12c8d091f984870a9b7ee3c4295cbee4/04Imperative/Script.fsx#L31-33

I can still reproduce it but can see that the scroll occurs but is not always to the very end of the file. To trigger the reformatting you would have to add some bad or different formatting to the code snippet, select the code to be reformated and then reformat it.

The version I am seeing it on is ...

Microsoft Visual Studio Ultimate 2015 CTP
Version 14.0.22609.0 D14REL
Microsoft .NET Framework
Version 4.6.00030

Installed Version: Ultimate

Architecture and Modeling Tools   00269-30000-00001-AA841
Microsoft Architecture and Modeling Tools
    
UML® and Unified Modeling Language™ are trademarks or registered trademarks of the Object Management Group, Inc. in the United States and other countries.

Visual Basic 2015 CTP   00269-30000-00001-AA841
Microsoft Visual Basic 2015 CTP

Visual C# 2015 CTP   00269-30000-00001-AA841
Microsoft Visual C# 2015 CTP

Visual C++ 2015 CTP   00269-30000-00001-AA841
Microsoft Visual C++ 2015 CTP

Visual F# 2015 RC   00269-30000-00001-AA841
Microsoft Visual F# 2015 RC

Visual Studio 2015 CTP Code Analysis Spell Checker   00269-30000-00001-AA841
Microsoft® Visual Studio® 2015 CTP Code Analysis Spell Checker

Portions of International CorrectSpell™ spelling correction system © 1993 by Lernout & Hauspie Speech Products N.V. All rights reserved.

The American Heritage® Dictionary of the English Language, Third Edition Copyright © 1992 Houghton Mifflin Company. Electronic version licensed from Lernout & Hauspie Speech Products N.V. All rights reserved.

Windows Phone SDK 8.0 - ENU   00269-30000-00001-AA841
Windows Phone SDK 8.0 - ENU

Application Insights Tools for Visual Studio Package   1.0
Application Insights Tools for Visual Studio

ASP.NET and Web Tools CTP   14.0.20206.0
ASP.NET and Web Tools CTP

ASP.NET Web Frameworks and Tools 2013   5.2.30130.0
For additional information, visit http://www.asp.net/

Common Azure Tools   1.3
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

ErrorList   1.0
Implementation of the Error and Task lists.

GenerateUnitTest   1.0
Generates unit test code for methods in classes under test.

Microsoft Azure Mobile Services Tools   1.3
Microsoft Azure Mobile Services Tools

Microsoft Code Digger   0.9
Microsoft Code Digger

Microsoft.Pex.VisualStudio   1.0
Pex

NuGet Package Manager   3.0.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PowerShell Tools   1.3
Provides file classification services using PowerShell

SQL Server Data Tools   14.0.50120.0
Microsoft SQL Server Data Tools

Visual F# Power Tools   1.8.0
Visual F# Power Tools

VsVim   1.8.0.0
VsVim is a Vim emulator for Visual Studio

**Comment by philderbeast** [comment] 2015-08-03 12:57
TODO: Try in vs2015 RTM.
