### ISSUE TITLE
Missing assemblies are not rechecked on each FCS query 

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/VisualFSharpPowerTools#1253] opened 2015-11-18 13:42 UTC
* clean a solution
* restart VS
* open a file
* almost no coloring since it cannot find referenced assemblies 
* build the solution
* **still no coloring**. Errors:

```
[VFPT][Information 04:37:50 ] [SyntaxConstructClassifier] FCS returns errors:
 [|startup (1,1)-(1,81) parameter error Assembly reference 'L:\hg\klsrl.core\Source\TestsCore\bin\Debug\TestsCore.dll' was not found or is invalid;
  startup (1,1)-(1,81) parameter error Assembly reference 'L:\hg\klsrl.core\Source\UnPackTools\bin\Debug\UnPackTools.dll' was not found or is invalid;
...
```
The assemblies are surely there.

**Comment by dungpa** [comment] 2015-11-19 06:55
So FCS still caches the old type checked results? What can we do to tell it not to do so?

**Comment by vasily-kirichenko** [comment] 2015-11-19 07:50
It seems it does:

![image](https://cloud.githubusercontent.com/assets/873919/11265169/0c1d14c4-8eab-11e5-91b8-b766a6c6396b.png)

Note that VFT works correctly, but we don't: Quick Info and the log show error. I think it's a major bug.

**Comment by vasily-kirichenko** [comment] 2015-11-19 07:53
Restarting VS has not fixed it (!) wow

**Comment by dungpa** [comment] 2015-11-21 00:06
I don't get it. The assemblies are there so a VS restart should fix it. Could you check whether assembly reference is always missing in FSharpProjectOptions?

**Comment by dungpa** [comment] 2016-04-24 22:55
Closing since we don't seem to reproduce it. 

Feel free to open another issue if it occurs again.

**Closed by dungpa** 2016-04-24 22:55 UTC
Labels: major-bug
