### ISSUE TITLE
Lint works fine. But it's difficult where is wrong.

### ISSUE THREAD

**Issue by omanuke** [fsprojects/VisualFSharpPowerTools#1158] opened 2015-10-13 04:22 UTC
Lint suggests where is wrong with wave under line, but it should be more wider.
With scroll bar map I can know approximate location, but wave line isn't obvious ,so I can't find location in detail.

**Comment by yukitos** [comment] 2015-10-13 04:52
Same here.
Only first 2 characters have wavy underline.
![image](https://cloud.githubusercontent.com/assets/1076180/10445748/98714d1c-71b1-11e5-9a3d-06db68d1deba.png)

**Comment by vasily-kirichenko** [comment] 2015-10-13 05:13
This is by design. If we underlined whole ranges FsLinter gives us, most of the code would be squiggled with orange.

**Comment by yukitos** [comment] 2015-10-13 05:22
Thank you for the clarification.
That makes sense :+1:

**Comment by omanuke** [comment] 2015-10-13 05:25
As u told,underlining whole range may be cumbersome, but still I feel it's not obvious. especially in white back ground. 
I tried another color like red, situation is same.
If you can give us an option of thickness of wavy line, it may work. Is it difficult?

**Comment by vasily-kirichenko** [comment] 2015-10-13 05:44
Yes, changing of how the wavy is rendered is difficult. Currently we just yielding error tags to VS and it show them as it want. To change the style we should switch to adormennts (that is what we use in Depth Colorizer feature). It seems possible, but need investigation and time.

**Comment by omanuke** [comment] 2015-10-13 06:04
make sense.
In dark background, orange wavy line is more noticeable.
I will try dark theme.
Thx.

**Comment by vasily-kirichenko** [comment] 2015-10-13 06:52
I'm all for adding settings for this, like maximum number of chars to highlight and the style of the wavy, fill free to add a separate issue with suggestions.

**Comment by dungpa** [comment] 2015-10-13 07:51
@omanuke F# Lint color can be changed here 

![image](https://cloud.githubusercontent.com/assets/941060/10448831/ce3de756-718f-11e5-836e-77097fc0ab27.png)

I hope it's enough to customize it for being more noticeable.

**Comment by omanuke** [comment] 2015-10-13 08:27
@dungpa I know it. But no color is suitable for me in white background.
Some color isn't obvious in white background and some color is similar to the color already used...

**Comment by dungpa** [comment] 2015-10-13 18:49
I'm closing this as being solved by #1164. Further feedback is welcome.

**Closed by dungpa** 2015-10-13 18:49 UTC
Labels: enhancement
