### ISSUE TITLE
"static let" breaks colorization

### ISSUE THREAD

**Issue by asik** [fsprojects/VisualFSharpPowerTools#1465] opened 2016-08-10 02:27 UTC
When a "static let" is used in a class, the class name is improperly colorized.

![Proper colorizing](http://imgur.com/mEHG2dK.png)

![Bad colorizing](http://imgur.com/kEbKESz.png)

This is on 2.5.0 in Visual Studio 2015 Update 3.

**Comment by abelbraaksma** [comment] 2016-10-17 12:13
I just tried to repro this, I can confirm it happens on my instance of VS 2015 (also Upd 3) as well.

**Comment by vasily-kirichenko** [comment] 2016-10-17 13:41
Fixed in https://github.com/fsprojects/VisualFSharpPowerTools/pull/1473

**Closed by vasily-kirichenko** 2016-10-17 13:41 UTC

**Comment by vasily-kirichenko** [comment] 2016-10-17 15:28
Grab 2.5.2 installer here https://github.com/fsprojects/VisualFSharpPowerTools/releases/download/2.5.2/FSharpVSPowerTools.vsix (I cannot upload it into VS gallery since it down or the like).

**Comment by vasily-kirichenko** [comment] 2016-10-19 11:35
Finally managed to push it to VS Gallery.
