### ISSUE TITLE
[Unused declarations] issue with nunit

### ISSUE THREAD

**Issue by xenocons** [fsprojects/VisualFSharpPowerTools#951] opened 2015-03-18 23:10 UTC
Hello,

I am not sure if this is an issue, but it seems now that I got Unused declarations working (sort of) with my current theme, it  highlights everything within a [<TestFixture>] as by nature these functions\methods are not referenced by other F# code.

Here is a screenshot (note that the scroll bar is populated with many warnings)

![image](https://cloud.githubusercontent.com/assets/3858449/6721351/6c1d9160-ce20-11e4-975f-3d81f34058b0.png)

As a side issue, it seems that with the VS color theme solarized, the source code syntax stuff doesn't put a squiggly grey mark under the unused declaration? Let me know if you want this opened as an issue.

Edit:updated screenshot to better demonstrate issue

**Comment by OkayX6** [comment] 2015-03-19 00:04
It is by design that attributes are not considered unused.
And unused declarations are simply grayed.

I am closing this for now, but if you would like to have it fixed, please consider creating a new request in our uservoice : https://vfpt.uservoice.com/

Thanks

**Closed by OkayX6** 2015-03-19 00:04 UTC
