### ISSUE TITLE
MissingReferencesException when trying to install Visual FSharp on Visual Studio 2015

### ISSUE THREAD

**Issue by tikae** [fsprojects/VisualFSharpPowerTools#1363] opened 2016-04-15 08:48 UTC
### Description

I recently installed VS2015 (and I ticked the option to install Visual FSharp). It completed installation with no issues. I know FSharp is installed because it recognises the file extension and some of the reserved words. I also have the Interactive window at the bottom. 

The issue is I have no syntax highlighting and other features found in the Visual F# Power Tools extension. When I try to install it, it fails with this message in the logs:

2016/04/15 10:23:31 AM - Microsoft VSIX Installer
2016/04/15 10:23:31 AM - -------------------------------------------
2016/04/15 10:23:31 AM - Initializing Install...
2016/04/15 10:23:31 AM - Extension Details...
2016/04/15 10:23:31 AM - Identifier         : FSharpVSPowerTools.68b42cfe-c752-4094-8dba-ed48aa81cac8
2016/04/15 10:23:31 AM - Name               : Visual F# Power Tools
2016/04/15 10:23:31 AM - Author             : fsharp.org
2016/04/15 10:23:31 AM - Version            : 2.3.0
2016/04/15 10:23:31 AM - Description        : A collection of additional commands for F# in Visual Studio
2016/04/15 10:23:31 AM - Locale             : en-US
2016/04/15 10:23:31 AM - MoreInfoURL        : https://github.com/fsprojects/VisualFSharpPowerTools
2016/04/15 10:23:31 AM - InstalledByMSI     : False
2016/04/15 10:23:31 AM - SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
2016/04/15 10:23:31 AM - 
2016/04/15 10:23:31 AM - SignatureState     : Unsigned
2016/04/15 10:23:31 AM - Supported Products : 
2016/04/15 10:23:31 AM - Microsoft.VisualStudio.Pro
2016/04/15 10:23:31 AM - Version : [12.0,13.0)
2016/04/15 10:23:31 AM - Microsoft.VisualStudio.Pro
2016/04/15 10:23:31 AM - Version : [13.0,15.0)
2016/04/15 10:23:31 AM - 
2016/04/15 10:23:31 AM - References         : 
2016/04/15 10:23:31 AM - 
-------------------------------------------------------
2016/04/15 10:23:31 AM - Identifier   : FSharp.Editor
2016/04/15 10:23:31 AM - Name         : Microsoft Visual FSharp Editor Extensions
2016/04/15 10:23:31 AM - Version      : [12.0,15.0)
2016/04/15 10:23:31 AM - MoreInfoURL  : http://www.microsoft.com/en-us/download/details.aspx?id=48179
2016/04/15 10:23:31 AM - Nested       : No
2016/04/15 10:23:31 AM - 2016/04/15 10:23:31 AM - Signature Details...
2016/04/15 10:23:31 AM - Extension is not signed.
2016/04/15 10:23:31 AM - 
2016/04/15 10:23:31 AM - Searching for applicable products...
2016/04/15 10:23:31 AM - Found installed product - Microsoft Visual Studio Professional 2013
2016/04/15 10:23:36 AM - An extension with a matching Identifier is already installed to this product.
2016/04/15 10:23:36 AM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
2016/04/15 10:23:36 AM - Found installed product - Microsoft Visual Studio Enterprise 2015
2016/04/15 10:23:42 AM - The extension with ID 'FSharpVSPowerTools.68b42cfe-c752-4094-8dba-ed48aa81cac8' is not installed to Microsoft Visual Studio Enterprise 2015.
2016/04/15 10:23:42 AM - Found installed product - Microsoft Visual Studio Professional 2015
2016/04/15 10:23:42 AM - Found installed product - Microsoft Visual Studio Community 2015
2016/04/15 10:23:42 AM - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
2016/04/15 10:23:42 AM - Found installed product - Global Location
2016/04/15 10:23:42 AM - Found installed product - ssms
2016/04/15 10:23:48 AM - The following target products have been selected...
2016/04/15 10:23:48 AM - Microsoft Visual Studio Enterprise 2015
2016/04/15 10:23:48 AM - 
2016/04/15 10:23:50 AM - Beginning to install extension to Microsoft Visual Studio Enterprise 2015...
2016/04/15 10:23:50 AM - Install Error : Microsoft.VisualStudio.ExtensionManager.MissingReferencesException: This extension cannot be installed because the following references are missing:
- Microsoft Visual FSharp Editor Extensions
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.CheckForInstallBlockers(InstallableExtensionImpl extension, IInstalledExtensionList modifiedInstalledExtensionsList, Boolean isNestedExtension, Boolean& olderVersionInstalled)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstallInternal(InstallableExtensionImpl extension, Boolean perMachine, Boolean isNestedExtension, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, UInt64 totalBytesToWrite, UInt64& totalBytesWritten, Boolean enforceCertificateCheckForUpgrade)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.BeginInstall(IInstallableExtension installableExtension, Boolean perMachine, AsyncOperation asyncOp, Boolean enforceCertificateCheckForUpgrade)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstallWorker(IInstallableExtension extension, Boolean perMachine, AsyncOperation asyncOp, Boolean enforceCertificateCheckForUpgrade)
___________________________________

When searching in Visual Studio (Tools -> Extensions and Updates -> Online) for the "Microsoft Visual FSharp Editor Extensions" mentioned in the logs it takes me to this site https://visualstudiogallery.msdn.microsoft.com/06b5edaf-9557-4987-b64e-f1722b015e86

I downloaded and installed the .exe succesfully but when I try install the F# Power Tools it still gives me the error above.

Please help me resolve this error, maybe I am approaching it in a wrong manner, but I simply want F# syntax highlighting, refactoring, formatting features. 

I am running a MacBook Pro with OSX 10.11 (El Capitan) with Windows 10 running in Parrallels,

Thanks.

**Comment by dungpa** [comment] 2016-04-15 10:21
This is a duplicate of #1354. Please use the latest build https://ci.appveyor.com/project/dungpa/visualfsharppowertools/branch/master/artifacts which should fix the issue.

**Comment by dungpa** [comment] 2016-04-20 13:43
Closing as duplicated.

**Closed by dungpa** 2016-04-20 13:43 UTC
Labels: duplicate
