### ISSUE TITLE
Generated references not in correct order

### ISSUE THREAD

**Issue by exercitusvir** [fsprojects/VisualFSharpPowerTools#1055] opened 2015-07-24 14:18 UTC
When a project (`P1`) references an assembly (`A`) and that project (`P1`) is referenced from another project (`P2`) in the same solution that also references that same assembly (`A`), then the command "Generate references for F# Interactive" does not necessarily generate references in the correct order. That's because it seems to use the order of declared references in the .fsproj file. 

For example, instead of generating the following correct order where both `P1` and `P2` depend on `A`:
```
A
P1
P2
```

the command generates the following incorrect order (based on the randomly declared order in the .fsproj file)

```
P1
A
P2
```

because it does not seem to recognize that both `P1` and `P2` reference `A` and that `A` needs to come before `P1` and `P2`.

F# Interactive will complain with a message along the lines of 
> Referencing type 'SomeType' from assembly 'A' that is not referenced

even though `A` is referenced in `load-references.fsx`, just too late. This is really confusing when you expect the command to do the right thing.

**Comment by dungpa** [comment] 2015-07-24 22:24
We already tried to use compiler reference resolution to ensure correct ordering?

Do you have a sample project that reproduces the issue? You can strip out all source files; we just need two project files with correct assembly references.

**Comment by isaacabraham** [comment] 2015-08-17 17:39
Is this on VS2013 or VS2015? F#3.x has a bug whereby if you have the same module declared in multiple files, you need to load files as separate execution steps rather than in one go.

I'm wondering if this is a similar sort of issue.

**Comment by exercitusvir** [comment] 2015-08-19 11:20
This is on VS 2013 with F# 3.1.

**Comment by dungpa** [comment] 2015-11-05 21:49
@exercitusvir I would like to fix this, but it's impossible without a real repro. Closing for now.

**Closed by dungpa** 2015-11-05 21:49 UTC
Labels: minor bug, no-repro

**Comment by halcwb** [comment] 2016-10-04 12:38
I can confirm this bug (see: http://stackoverflow.com/questions/20346793/hacking-referenced-assemblies/29037630#29037630). This is still happening with VS2015 and the latest powertools version. 

See this repository: https://github.com/halcwb/GenPDMS/commit/415f966cba7cf2a1493a006864475dd39f46e9e8.
When you revert the change than you run into an error when trying to run the `runWith` function. 
The problem is that GenPDMS was referenced before Suave, while GenPDMS uses Suave. This causes the script to fail in the fsi.
