### ISSUE TITLE
Lint on fresh install on VS 2015 - property page error

### ISSUE THREAD

**Issue by Andrea** [fsprojects/VisualFSharpPowerTools#1163] opened 2015-10-13 13:07 UTC
Hi there

It seems like this hasn't been reported here before. 
I just installed VS 2015 release community edition and added Fsharp Power tools (restarted just for the craic) and this is what I see on the property page for lint 

![image](https://cloud.githubusercontent.com/assets/3103/10455508/a84d2db2-71b3-11e5-8b9c-38db97fdc426.png)

if you want me to debug I could use some instructions :D

**Comment by dungpa** [comment] 2015-10-13 13:18
@Andrea I have a few questions:

1. Does any feature work in your installation?
2. Is there any F# Power Tools entry in C:\Users<user name>\AppData\Roaming\Microsoft\VisualStudio\14.0\ActivityLog.xml?

Thanks.

**Comment by Andrea** [comment] 2015-10-13 13:34
1) yes, I see the track lines and unused code is greyed out
2) Just the begin and end package load
I searched as fsharp power tools f#... fs... and this one is the one that made the most send
```
  <entry>
    <record>116</record>
    <time>2015/10/13 13:31:23.158</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>End package load [PowerToolsCommandsPackage]</description>
    <guid>{F152487E-9A22-4CF9-BEE6-A8F7C77F828D}</guid>
  </entry>
```

**Comment by dungpa** [comment] 2015-10-13 20:19
Unfortunately, there was no error in the log.

I produced a new build v2.1.1 that includes some more logging https://ci.appveyor.com/project/dungpa/visualfsharppowertools/build/2.2.0-a1510132010/artifacts. 

If you install this version and enable Diagnostics mode http://fsprojects.github.io/VisualFSharpPowerTools/faq.html#What-is-Diagnostic-mode-When-should-I-use-it, there might be additional information for us to find out the root cause. Thanks.

**Comment by dungpa** [comment] 2015-10-14 08:30
@Andrea We pushed a fix at https://github.com/fsprojects/VisualFSharpPowerTools/pull/1166. Could you verify this build whether the bug is gone https://ci.appveyor.com/project/dungpa/visualfsharppowertools/build/2.2.0-a1510140720/artifacts . Thanks.

**Comment by Andrea** [comment] 2015-10-14 09:18
Thanks, I just installed it and tried it and now when I go to the lint tab in options is totally empty  :|

This is all relevant log info, but I don't see anything too useful here.
```
<entry>
    <record>1770</record>
    <time>2015/10/14 09:05:44.952</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Importing pkgdef file</description>
    <path>C:\Users\edited\AppData\Local\Microsoft\VisualStudio\14.0\Extensions\ub1s0dns.2yg\FSharpVSPowerTools.pkgdef</path>
  </entry>

...

  <entry>
    <record>1869</record>
    <time>2015/10/14 09:05:51.843</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [PowerToolsCommandsPackage]</description>
    <guid>{F152487E-9A22-4CF9-BEE6-A8F7C77F828D}</guid>
  </entry>

  <entry>
    <record>2099</record>
    <time>2015/10/14 09:06:00.727</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>End package load [PowerToolsCommandsPackage]</description>
    <guid>{F152487E-9A22-4CF9-BEE6-A8F7C77F828D}</guid>
  </entry>

```

Since this plug in is also installed on my VS2013 version (Ultimate) I went to check it out there and there is also an empty screen on lint
![image](https://cloud.githubusercontent.com/assets/3103/10479532/e200eb8a-725c-11e5-8ef4-ea03d56fd294.png)

**Comment by dungpa** [comment] 2015-10-14 09:21
Could you enable Diagnostics mode and check Output windows (or ActivityLog.xml) again http://fsprojects.github.io/VisualFSharpPowerTools/faq.html#What-is-Diagnostic-mode-When-should-I-use-it? In general, it needs a F# project being opened in VS in order to show appropriate settings.

**Comment by Andrea** [comment] 2015-10-14 09:32
on VS2013
when you go to the Lint window option
```
[VFPT][Error 10:28:07 ] Exception Message: 'Cannot set unknown member 'System.Windows.Interactivity.InvokeCommandAction.Command'.' Line number '84' and line position '45'.
Stack Trace:    at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, Boolean skipJournaledProperties, Uri baseUri)
   at System.Windows.Markup.XamlReader.Load(XamlReader xamlReader, ParserContext parserContext)
   at System.Windows.Markup.XamlReader.Load(XmlReader reader, ParserContext parserContext, XamlParseMode parseMode)
   at System.Windows.Markup.XamlReader.Load(Stream stream, ParserContext parserContext)
   at System.Windows.Markup.XamlReader.Load(Stream stream)
   at FsXaml.LoadXaml.from[a](String file, Type t)
   at FsXaml.FactoryUtilities.loadChildIfNull[a,b](a root, String resourceFile, b self)
   at FsXaml.XamlContainer..ctor(FrameworkElement content, String resourceFile)
   at FSharpVSPowerTools.Linting.LintOptionsControlProvider..ctor()
   at <StartupCode$FSharpVSPowerTools-Logic>.$LintOptionsPage.-ctor@26-182.Invoke(Unit unitVar)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at <StartupCode$FSharpVSPowerTools-Logic>.$LintOptionsPage.get_Child@122.Invoke(Unit _arg3)
   at FSharpVSPowerTools.ProjectSystem.VSUtils.protectOrDefault[a](FSharpFunc`2 f, a defaultVal)
[VFPT][Error 10:28:08 ] Exception Message: 'Cannot set unknown member 'System.Windows.Interactivity.InvokeCommandAction.Command'.' Line number '84' and line position '45'.
Stack Trace:    at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, Boolean skipJournaledProperties, Uri baseUri)
   at System.Windows.Markup.XamlReader.Load(XamlReader xamlReader, ParserContext parserContext)
   at System.Windows.Markup.XamlReader.Load(XmlReader reader, ParserContext parserContext, XamlParseMode parseMode)
   at System.Windows.Markup.XamlReader.Load(Stream stream, ParserContext parserContext)
   at System.Windows.Markup.XamlReader.Load(Stream stream)
   at FsXaml.LoadXaml.from[a](String file, Type t)
   at FsXaml.FactoryUtilities.loadChildIfNull[a,b](a root, String resourceFile, b self)
   at FsXaml.XamlContainer..ctor(FrameworkElement content, String resourceFile)
   at FSharpVSPowerTools.Linting.LintOptionsControlProvider..ctor()
   at <StartupCode$FSharpVSPowerTools-Logic>.$LintOptionsPage.-ctor@26-182.Invoke(Unit unitVar)
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at <StartupCode$FSharpVSPowerTools-Logic>.$LintOptionsPage.OnActivate@86.Invoke(Unit _arg2)
   at FSharpVSPowerTools.ProjectSystem.VSUtils.protectOrDefault[a](FSharpFunc`2 f, a defaultVal)
[VFPT][Error 10:28:10 ] Exception Message: 'Cannot set unknown member 'System.Windows.Interactivity.InvokeCommandAction.Command'.' Line number '84' and line position '45'.
Stack Trace:    at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, Boolean skipJournaledProperties, Uri baseUri)
   at System.Windows.Markup.XamlReader.Load(XamlReader xamlReader, ParserContext parserContext)
   at System.Windows.Markup.XamlReader.Load(XmlReader reader, ParserContext parserContext, XamlParseMode parseMode)
   at System.Windows.Markup.XamlReader.Load(Stream stream, ParserContext parserContext)
   at System.Windows.Markup.XamlReader.Load(Stream stream)
   at FsXaml.LoadXaml.from[a](String file, Type t)
   at FsXaml.FactoryUtilities.loadChildIfNull[a,b](a root, String resourceFile, b self)
   at FsXaml.XamlContainer..ctor(FrameworkElement content, String resourceFile)
   at FSharpVSPowerTools.Linting.LintOptionsControlProvider..ctor()
   at <StartupCode$FSharpVSPowerTools-Logic>.$LintOptionsPage.-ctor@26-182.Invoke(Unit unitVar)
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at <StartupCode$FSharpVSPowerTools-Logic>.$LintOptionsPage.OnApply@78.Invoke(Unit _arg1)
   at FSharpVSPowerTools.ProjectSystem.VSUtils.protectOrDefault[a](FSharpFunc`2 f, a defaultVal)
```


And from VS2015 , same scenatrio 

```
[VFPT][Error 10:31:38 ] Exception Message: 'Cannot set unknown member 'System.Windows.Interactivity.InvokeCommandAction.Command'.' Line number '84' and line position '45'.
Stack Trace:    at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, Boolean skipJournaledProperties, Uri baseUri)
   at System.Windows.Markup.XamlReader.Load(XamlReader xamlReader, ParserContext parserContext)
   at System.Windows.Markup.XamlReader.Load(XmlReader reader, ParserContext parserContext, XamlParseMode parseMode)
   at System.Windows.Markup.XamlReader.Load(Stream stream, ParserContext parserContext)
   at System.Windows.Markup.XamlReader.Load(Stream stream)
   at FsXaml.LoadXaml.from[a](String file, Type t)
   at FsXaml.FactoryUtilities.loadChildIfNull[a,b](a root, String resourceFile, b self)
   at FsXaml.XamlContainer..ctor(FrameworkElement content, String resourceFile)
   at FSharpVSPowerTools.Linting.LintOptionsControlProvider..ctor()
   at <StartupCode$FSharpVSPowerTools-Logic>.$LintOptionsPage.-ctor@26-182.Invoke(Unit unitVar)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at <StartupCode$FSharpVSPowerTools-Logic>.$LintOptionsPage.get_Child@122.Invoke(Unit _arg3)
   at FSharpVSPowerTools.ProjectSystem.VSUtils.protectOrDefault[a](FSharpFunc`2 f, a defaultVal)
[VFPT][Error 10:31:38 ] Exception Message: 'Cannot set unknown member 'System.Windows.Interactivity.InvokeCommandAction.Command'.' Line number '84' and line position '45'.
Stack Trace:    at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, Boolean skipJournaledProperties, Uri baseUri)
   at System.Windows.Markup.XamlReader.Load(XamlReader xamlReader, ParserContext parserContext)
   at System.Windows.Markup.XamlReader.Load(XmlReader reader, ParserContext parserContext, XamlParseMode parseMode)
   at System.Windows.Markup.XamlReader.Load(Stream stream, ParserContext parserContext)
   at System.Windows.Markup.XamlReader.Load(Stream stream)
   at FsXaml.LoadXaml.from[a](String file, Type t)
   at FsXaml.FactoryUtilities.loadChildIfNull[a,b](a root, String resourceFile, b self)
   at FsXaml.XamlContainer..ctor(FrameworkElement content, String resourceFile)
   at FSharpVSPowerTools.Linting.LintOptionsControlProvider..ctor()
   at <StartupCode$FSharpVSPowerTools-Logic>.$LintOptionsPage.-ctor@26-182.Invoke(Unit unitVar)
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at <StartupCode$FSharpVSPowerTools-Logic>.$LintOptionsPage.OnActivate@86.Invoke(Unit _arg2)
   at FSharpVSPowerTools.ProjectSystem.VSUtils.protectOrDefault[a](FSharpFunc`2 f, a defaultVal)
[VFPT][Error 10:31:40 ] Exception Message: 'Cannot set unknown member 'System.Windows.Interactivity.InvokeCommandAction.Command'.' Line number '84' and line position '45'.
Stack Trace:    at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, Boolean skipJournaledProperties, Uri baseUri)
   at System.Windows.Markup.XamlReader.Load(XamlReader xamlReader, ParserContext parserContext)
   at System.Windows.Markup.XamlReader.Load(XmlReader reader, ParserContext parserContext, XamlParseMode parseMode)
   at System.Windows.Markup.XamlReader.Load(Stream stream, ParserContext parserContext)
   at System.Windows.Markup.XamlReader.Load(Stream stream)
   at FsXaml.LoadXaml.from[a](String file, Type t)
   at FsXaml.FactoryUtilities.loadChildIfNull[a,b](a root, String resourceFile, b self)
   at FsXaml.XamlContainer..ctor(FrameworkElement content, String resourceFile)
   at FSharpVSPowerTools.Linting.LintOptionsControlProvider..ctor()
   at <StartupCode$FSharpVSPowerTools-Logic>.$LintOptionsPage.-ctor@26-182.Invoke(Unit unitVar)
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at <StartupCode$FSharpVSPowerTools-Logic>.$LintOptionsPage.OnApply@78.Invoke(Unit _arg1)
   at FSharpVSPowerTools.ProjectSystem.VSUtils.protectOrDefault[a](FSharpFunc`2 f, a defaultVal)

```

**Comment by dungpa** [comment] 2015-10-14 09:42
I think I posted two different VFPT versions in this thread. The first one adds logging and the second one contains a fix. Could you try to install the second version https://ci.appveyor.com/project/dungpa/visualfsharppowertools/build/2.2.0-a1510140720/artifacts ? Notice that the two versions have different timestamps. You have to uninstall the first version before installing this one.

Sorry for the inconveniences.

**Comment by Andrea** [comment] 2015-10-14 09:51
Huge sucess!! I thought I had installed that one (didn't realise I had to uninstall) 

![image](https://cloud.githubusercontent.com/assets/3103/10480318/7e2acad6-7261-11e5-95ec-c1638e76afc3.png)

**Comment by dungpa** [comment] 2015-10-14 10:20
Thanks. I'm closing this issue as fixed.

**Closed by dungpa** 2015-10-14 10:20 UTC
Labels: bug

**Comment by Andrea** [comment] 2015-10-14 10:44
Thanks to you :D

Andrea
www.roundcrisis.com
