### ISSUE TITLE
Syntax Coloring reverts to default on Hibernate/Sleep/Remote Access

### ISSUE THREAD

**Issue by caseykramer** [fsprojects/VisualFSharpPowerTools#990] opened 2015-06-02 15:27 UTC
I think the only reason I noticed this was because a regularly work on a laptop and and I have a dark color scheme with highly customized colors.

If the machine goes to sleep, hibernates, or if there is a remote desktop connection (occurs both when the remote connection is initiated, and when you log back in to the machine after a remote connection) the colors appear to revert to their default settings, which in my case means I can't see a lot of the code. This doesn't correct itself until I close/reopen visual studio.

I noticed this with VS2012 and VS2013. I've not tried VS2015 yet.

Let me know if there is any additional info that would be useful tracking this down.

**Comment by dungpa** [comment] 2015-06-04 08:46
Thanks for letting us know.

I find it really strange because synchronization is handled by Visual Studio. Perhaps It is related to VS behaviors where they sync settings across machines.

You can disable synchronization by:
 - Go to `Environment --> Synchronized Settings`
 - Uncheck `Appearance (Theme, Fonts and Colors)

Could you give it a try?

**Comment by caseykramer** [comment] 2015-06-09 14:12
Doesn't look like that helped. It seemed to do ok if I put the machine to sleep and then woke it back up, but making an RDP connection still caused the colors to go all strange.

I've attached before and after screen caps just in case that is helpful. If there is any additional info I can get to help debug let me know and I would be happy to do so.

![before](https://cloud.githubusercontent.com/assets/228024/8059804/e14812d0-0e8f-11e5-97bd-c3f62f3dedb4.png)
![after](https://cloud.githubusercontent.com/assets/228024/8059807/e3a5a20e-0e8f-11e5-899d-10ea047e4445.png)

**Comment by vasily-kirichenko** [comment] 2015-11-21 13:39
Yes, the colors have been always reverted to defaults after accessing to a machine by RDP.

Today I've spot another (related?) issue: when you switch themes, colors are also reset to defaults. 

I think the problem is here https://github.com/fsprojects/VisualFSharpPowerTools/blob/master/src/FSharpVSPowerTools/Commands/SyntaxConstructClassifierProvider.cs#L195-L223

**Comment by dungpa** [comment] 2015-11-21 15:57
You're right. Will attempt to fix this issue soon.

**Comment by vasily-kirichenko** [comment] 2015-11-21 16:20
@dungpa I've tried this https://github.com/vasily-kirichenko/FSharpVSPowerTools/commit/0fbd23ba955e11b3f027ce8f382cb592e9b5da74 

So the algorithm on theme changing event:

* Get the color from "old" props
* If it's not equal to the default ident color for the new theme, use it
* Otherwise, use our default color.

It does not work for all scenarios, for example:

* Choose a yellow color for for Functions in Blue theme.
* Switch to Dark theme - the color is yellow, but must be the default.
* Set some other color.
* Now colors are OK in both themes.

**Comment by dungpa** [comment] 2015-11-22 01:26
@caseykramer @vasily-kirichenko Could you guys help verify this fix https://ci.appveyor.com/project/dungpa/visualfsharppowertools/build/2.2.0-a1511220119/artifacts? I'm sorry that it takes so long to realize the mistake.

@vasily-kirichenko My fix is specifically for this issue. It doesn't fix color reset when switching themes, which is addressed by your changes above.

**Closed** 2015-11-22 15:28 UTC
Labels: minor bug
