### ISSUE TITLE
Microsoft.VisualStudio.ExtensionManager.MissingReferencesException

### ISSUE THREAD

**Issue by gwinsky** [fsprojects/VisualFSharpPowerTools#1362] opened 2016-04-15 08:35 UTC
### Description

Microsoft.VisualStudio.ExtensionManager.MissingReferencesException
while installing.

### Repro steps

When trying to install 2.3.0 in 
VS 2015 Community, update 2 , inkl F# 4.0
on latest Win 7
I get a Microsoft.VisualStudio.ExtensionManager.MissingReferencesException

Is this a problem in VFSPT or with my VS2015 installation?

see log file attached.
[VSIXInstaller_b1fef609-40e0-461b-bca1-4efb1c04af25.txt](https://github.com/fsprojects/VisualFSharpPowerTools/files/220582/VSIXInstaller_b1fef609-40e0-461b-bca1-4efb1c04af25.txt)

**Comment by dungpa** [comment] 2016-04-15 10:22
This is a duplicate of #1354. Please use the latest build https://ci.appveyor.com/project/dungpa/visualfsharppowertools/branch/master/artifacts which should fix the issue.

**Comment by gwinsky** [comment] 2016-04-15 11:58
this worked! thanks!

**Comment by vasily-kirichenko** [comment] 2016-04-15 11:59
@dungpa maybe it's time for a new release?

**Closed by vasily-kirichenko** 2016-04-15 11:59 UTC

**Comment by dungpa** [comment] 2016-04-15 13:15
@vasily-kirichenko Probably yes. Would you like to add something before doing so?

**Comment by vasily-kirichenko** [comment] 2016-04-15 14:06
@dungpa no
