### ISSUE TITLE
VisualStudio 2015 + dark theme + F# power tools ==> white background

### ISSUE THREAD

**Issue by pchalamet** [fsprojects/VisualFSharpPowerTools#1051] opened 2015-07-22 21:11 UTC
Using VS2015 + dark theme with default color scheme looks fine.
But when importing exported color scheme from VS2013 (with F# powertools colors), it leads to white background all the time.
Expecting default background color for dark theme to be used.

**Comment by dungpa** [comment] 2015-07-22 21:29
Do you have a stripped down version of VS setting file for me to test? That is, you choose Export settings, choose exporting only Fonts and Colors (including Power Tools colors).

**Comment by pchalamet** [comment] 2015-07-22 21:56
Sure.

```xml
<UserSettings>
	<ApplicationIdentity version="12.0"/>
	<Category name="Environment_Group" RegisteredName="Environment_Group">
		<Category name="Environment_FontsAndColors" Category="{1EDA5DD4-927A-43a7-810E-7FD247D0DA1D}" Package="{DA9FB551-C724-11d0-AE1F-00A0C90FFFC3}" RegisteredName="Environment_FontsAndColors" PackageName="Visual Studio Environment Package">
			<PropertyValue name="Version">2</PropertyValue>
			<FontsAndColors Version="2.0">
				<Theme Id="{1DED0138-47CE-435E-84EF-9EC1F439B749}"/>
				<Categories>
					<Category GUID="{00CCEE86-3140-4E06-A65A-A92665A40D6F}" FontIsDefault="Yes">
						<Items>
							<Item Name="Plain Text" Foreground="0x02000000" Background="0x02000000" BoldFont="No"/>
							<Item Name="Selected Text" Foreground="0x02000000" Background="0x02000000" BoldFont="No"/>
						</Items>
					</Category>
					<Category GUID="{40660F54-80FA-4375-89A3-8D06AA954EBA}" FontName="Droid Sans Mono" FontSize="9" CharSet="0" FontIsDefault="No">
						<Items>
							<Item Name="Plain Text" Foreground="0x0000FF80" Background="0x00303030" BoldFont="No"/>
							<Item Name="Selected Text" Foreground="0x02000000" Background="0x02000000" BoldFont="No"/>
							<Item Name="Inactive Selected Text" Foreground="0x02000000" Background="0x02000000" BoldFont="No"/>
						</Items>
					</Category>
					<Category GUID="{58E96763-1D3B-4E05-B6BA-FF7115FD0B7B}" FontName="Consolas" FontSize="11" CharSet="0" FontIsDefault="No">
						<Items>
							<Item Name="Plain Text" Foreground="0x00E8E8E8" Background="0x00202020" BoldFont="No"/>
							<Item Name="Selected Text" Foreground="0x00FFFFFF" Background="0x004080FF" BoldFont="No"/>
							<Item Name="Inactive Selected Text" Foreground="0x00808080" Background="0x00808080" BoldFont="No"/>
							<Item Name="Indicator Margin" Foreground="0x02000000" Background="0x00202020" BoldFont="No"/>
						</Items>
					</Category>
					<Category GUID="{5C48B2CB-0366-4FBF-9786-0BB37E945687}" FontName="Droid Sans Mono" FontSize="9" CharSet="0" FontIsDefault="No">
						<Items>
							<Item Name="Plain Text" Foreground="0x0000FF80" Background="0x00303030" BoldFont="No"/>
							<Item Name="Selected Text" Foreground="0x02000000" Background="0x02000000" BoldFont="No"/>
							<Item Name="Inactive Selected Text" Foreground="0x02000000" Background="0x02000000" BoldFont="No"/>
							<Item Name="Current List Location" Foreground="0x00A3DBFF" Background="0x01000007" BoldFont="No"/>
						</Items>
					</Category>
					<Category GUID="{6BB65C5A-2F31-4BDE-9F48-8A38DC0C63E7}" FontName="Droid Sans Mono" FontSize="9" CharSet="0" FontIsDefault="No">
						<Items>
							<Item Name="Plain Text" Foreground="0x0000FF80" Background="0x00303030" BoldFont="No"/>
							<Item Name="Selected Text" Foreground="0x02000000" Background="0x02000000" BoldFont="No"/>
							<Item Name="Inactive Selected Text" Foreground="0x02000000" Background="0x02000000" BoldFont="No"/>
						</Items>
					</Category>
					<Category GUID="{75A05685-00A8-4DED-BAE5-E7A50BFA929A}" FontName="Consolas" FontSize="11" CharSet="0" FontIsDefault="No">
						<Items>
							<Item Name="ReSharper Todo Item" Foreground="0x00FACE87" Background="0x01000001" BoldFont="No"/>
							<Item Name="Comment" Foreground="0x0000AA00" Background="0x02000000" BoldFont="No"/>
							<Item Name="Keyword" Foreground="0x004080FF" Background="0x02000000" BoldFont="No"/>
							<Item Name="Preprocessor Keyword" Foreground="0x00FF80FF" Background="0x02000000" BoldFont="No"/>
							<Item Name="Operator" Foreground="0x00FFFFFF" Background="0x02000000" BoldFont="No"/>
							<Item Name="String" Foreground="0x007280FA" Background="0x02000000" BoldFont="No"/>
							<Item Name="Number" Foreground="0x0000FF80" Background="0x02000000" BoldFont="No"/>
							<Item Name="CurrentLineActiveFormat" Foreground="0x00282828" Background="0x00282828" BoldFont="No"/>
							<Item Name="urlformat" Foreground="0x0000FFFF" Background="0x02000000" BoldFont="No"/>
							<Item Name="Selected Text" Foreground="0x00FFFFFF" Background="0x004080FF" BoldFont="No"/>
							<Item Name="Inactive Selected Text" Foreground="0x00808080" Background="0x00808080" BoldFont="No"/>
							<Item Name="MarkerFormatDefinition/HighlightedReference" Foreground="0x02000000" Background="0x00C08080" BoldFont="No"/>
							<Item Name="XML Doc Comment" Foreground="0x006BB7BD" Background="0x02000000" BoldFont="No"/>
							<Item Name="XML Doc Tag" Foreground="0x0000AA00" Background="0x02000000" BoldFont="No"/>
							<Item Name="CSS Comment" Foreground="0x00C080FF" Background="0x02000000" BoldFont="No"/>
							<Item Name="CSS Keyword" Foreground="0x00FFC440" Background="0x02000000" BoldFont="No"/>
							<Item Name="CSS Selector" Foreground="0x00A9F1FE" Background="0x02000000" BoldFont="No"/>
							<Item Name="CSS Property Name" Foreground="0x00FFC440" Background="0x02000000" BoldFont="No"/>
							<Item Name="CSS Property Value" Foreground="0x00F1C7C7" Background="0x02000000" BoldFont="No"/>
							<Item Name="CSS String Value" Foreground="0x0060FF60" Background="0x02000000" BoldFont="No"/>
							<Item Name="HTML Attribute" Foreground="0x007280FA" Background="0x02000000" BoldFont="No"/>
							<Item Name="HTML Attribute Value" Foreground="0x0071DF87" Background="0x02000000" BoldFont="No"/>
							<Item Name="HTML Comment" Foreground="0x00A0D0D0" Background="0x02000000" BoldFont="No"/>
							<Item Name="HTML Element Name" Foreground="0x00CEE07E" Background="0x02000000" BoldFont="No"/>
							<Item Name="HTML Entity" Foreground="0x00CEE07E" Background="0x02000000" BoldFont="No"/>
							<Item Name="HTML Operator" Foreground="0x00D0D0D0" Background="0x02000000" BoldFont="No"/>
							<Item Name="HTML Server-Side Script" Foreground="0x00000000" Background="0x00D7D7D7" BoldFont="No"/>
							<Item Name="HTML Tag Delimiter" Foreground="0x00CEE07E" Background="0x02000000" BoldFont="No"/>
							<Item Name="FSharp.Function" Foreground="0x0000FF00" Background="0x01000001" BoldFont="No"/>
						</Items>
					</Category>
					<Category GUID="{8259ACED-490A-41B3-A0FB-64C842CCDC80}" FontName="Tahoma" FontSize="8" CharSet="0" FontIsDefault="No">
						<Items/>
					</Category>
					<Category GUID="{9973EFDF-317D-431C-8BC1-5E88CBFD4F7F}" FontName="Droid Sans Mono" FontSize="9" CharSet="0" FontIsDefault="No">
						<Items>
							<Item Name="Plain Text" Foreground="0x0000FF80" Background="0x00303030" BoldFont="No"/>
							<Item Name="Selected Text" Foreground="0x02000000" Background="0x02000000" BoldFont="No"/>
							<Item Name="Inactive Selected Text" Foreground="0x02000000" Background="0x02000000" BoldFont="No"/>
							<Item Name="Current List Location" Foreground="0x00A3DBFF" Background="0x01000007" BoldFont="No"/>
						</Items>
					</Category>
					<Category GUID="{9E632E6E-D786-4F9A-8D3E-B9398836C784}" FontName="Droid Sans Mono" FontSize="9" CharSet="0" FontIsDefault="No">
						<Items>
							<Item Name="Plain Text" Foreground="0x0000FF80" Background="0x00303030" BoldFont="No"/>
							<Item Name="Selected Text" Foreground="0x02000000" Background="0x02000000" BoldFont="No"/>
							<Item Name="Inactive Selected Text" Foreground="0x02000000" Background="0x02000000" BoldFont="No"/>
						</Items>
					</Category>
					<Category GUID="{A7EE6BEE-D0AA-4B2F-AD9D-748276A725F6}" FontName="Tahoma" FontSize="8" CharSet="0" FontIsDefault="No">
						<Items/>
					</Category>
					<Category GUID="{A9A5637F-B2A8-422E-8FB5-DFB4625F0111}" FontName="Tahoma" FontSize="8" CharSet="0" FontIsDefault="No">
						<Items/>
					</Category>
					<Category GUID="{B36B0228-DBAD-4DB0-B9C7-2AD3E572010F}" FontName="Segoe UI" FontSize="9" CharSet="1" FontIsDefault="No">
						<Items>
							<Item Name="Different content" Foreground="0x000014E5" Background="0x00FFFFFF" BoldFont="No"/>
							<Item Name="Identical content" Foreground="0x00000000" Background="0x00FFFFFF" BoldFont="No"/>
							<Item Name="Source Only" Foreground="0x00000000" Background="0x00FFFFFF" BoldFont="No"/>
							<Item Name="Target Only" Foreground="0x00000000" Background="0x00FFFFFF" BoldFont="No"/>
							<Item Name="Not Downloaded" Foreground="0x00999999" Background="0x00FFFFFF" BoldFont="No"/>
							<Item Name="Even Row Items" Foreground="0x00000000" Background="0x00FFFFFF" BoldFont="No"/>
							<Item Name="Odd Row Items" Foreground="0x00000000" Background="0x00FFFFFF" BoldFont="No"/>
						</Items>
					</Category>
					<Category GUID="{BB8FE807-A186-404A-81FA-D20B908CA93B}" FontName="Tahoma" FontSize="8" CharSet="0" FontIsDefault="No">
						<Items/>
					</Category>
					<Category GUID="{C1614BB1-734F-4A31-BD42-5AE6275E16D2}" FontName="Tahoma" FontSize="8" CharSet="0" FontIsDefault="No">
						<Items/>
					</Category>
					<Category GUID="{CE2ECED5-C21C-464C-9B45-15E10E9F9EF9}" FontName="Droid Sans Mono" FontSize="9" CharSet="0" FontIsDefault="No">
						<Items>
							<Item Name="Plain Text" Foreground="0x0000FF80" Background="0x00303030" BoldFont="No"/>
							<Item Name="Selected Text" Foreground="0x02000000" Background="0x02000000" BoldFont="No"/>
							<Item Name="Inactive Selected Text" Foreground="0x02000000" Background="0x02000000" BoldFont="No"/>
						</Items>
					</Category>
					<Category GUID="{E0187991-B458-4F7E-8CA9-42C9A573B56C}" FontName="Consolas" FontSize="11" CharSet="0" FontIsDefault="No">
						<Items>
							<Item Name="Keyword" Foreground="0x004080FF" Background="0x02000000" BoldFont="No"/>
							<Item Name="Comment" Foreground="0x0000AA00" Background="0x02000000" BoldFont="No"/>
							<Item Name="String" Foreground="0x007280FA" Background="0x02000000" BoldFont="No"/>
							<Item Name="Number" Foreground="0x0000FF80" Background="0x02000000" BoldFont="No"/>
							<Item Name="XML Doc Comment" Foreground="0x006BB7BD" Background="0x02000000" BoldFont="No"/>
							<Item Name="XML Doc Tag" Foreground="0x0000AA00" Background="0x02000000" BoldFont="No"/>
							<Item Name="XML Doc Attribute" Foreground="0x0000BE00" Background="0x02000000" BoldFont="No"/>
							<Item Name="XML CData Section" Foreground="0x00ADADAD" Background="0x02000000" BoldFont="No"/>
							<Item Name="String(C# @ Verbatim)" Foreground="0x007280FA" Background="0x02000000" BoldFont="No"/>
							<Item Name="Operator" Foreground="0x00FFFFFF" Background="0x02000000" BoldFont="No"/>
							<Item Name="Preprocessor Keyword" Foreground="0x00FF80FF" Background="0x02000000" BoldFont="No"/>
							<Item Name="User Types" Foreground="0x006BCBFE" Background="0x02000000" BoldFont="No"/>
							<Item Name="User Types(Value types)" Foreground="0x006BCBFE" Background="0x02000000" BoldFont="No"/>
							<Item Name="User Types(Interfaces)" Foreground="0x00CEE07E" Background="0x02000000" BoldFont="No"/>
							<Item Name="User Types(Delegates)" Foreground="0x0000FFFF" Background="0x02000000" BoldFont="No"/>
							<Item Name="User Types(Enums)" Foreground="0x006BCBFE" Background="0x02000000" BoldFont="No"/>
							<Item Name="Stale Code" Foreground="0x00FF409F" Background="0x02000000" BoldFont="No"/>
							<Item Name="Memory Changed" Foreground="0x004080FF" Background="0x02000000" BoldFont="No"/>
							<Item Name="XAML Text" Foreground="0x00D0D0D0" Background="0x02000000" BoldFont="No"/>
							<Item Name="XAML Keyword" Foreground="0x00CEE07E" Background="0x02000000" BoldFont="No"/>
							<Item Name="XAML Delimiter" Foreground="0x00CEE07E" Background="0x02000000" BoldFont="No"/>
							<Item Name="XAML Comment" Foreground="0x00A0D0D0" Background="0x02000000" BoldFont="No"/>
							<Item Name="XAML Name" Foreground="0x00CEE07E" Background="0x02000000" BoldFont="No"/>
							<Item Name="XAML Attribute" Foreground="0x007280FA" Background="0x02000000" BoldFont="No"/>
							<Item Name="XAML CData Section" Foreground="0x00ADADAD" Background="0x02000000" BoldFont="No"/>
							<Item Name="XAML Attribute Value" Foreground="0x0071DF87" Background="0x02000000" BoldFont="No"/>
							<Item Name="XAML Attribute Quotes" Foreground="0x0071DF87" Background="0x02000000" BoldFont="No"/>
							<Item Name="XAML Markup Extension Class" Foreground="0x0000FF80" Background="0x02000000" BoldFont="No"/>
							<Item Name="XAML Markup Extension Parameter Name" Foreground="0x00CEE07E" Background="0x02000000" BoldFont="No"/>
							<Item Name="XAML Markup Extension Parameter Value" Foreground="0x00D0D0D0" Background="0x02000000" BoldFont="No"/>
							<Item Name="XML Text" Foreground="0x00D0D0D0" Background="0x02000000" BoldFont="No"/>
							<Item Name="XML Keyword" Foreground="0x00CEE07E" Background="0x02000000" BoldFont="No"/>
							<Item Name="XML Delimiter" Foreground="0x00CEE07E" Background="0x02000000" BoldFont="No"/>
							<Item Name="XML Name" Foreground="0x00CEE07E" Background="0x02000000" BoldFont="No"/>
							<Item Name="XML Attribute" Foreground="0x007280FA" Background="0x02000000" BoldFont="No"/>
							<Item Name="XML Attribute Value" Foreground="0x0071DF87" Background="0x02000000" BoldFont="No"/>
							<Item Name="XML Attribute Quotes" Foreground="0x0071DF87" Background="0x02000000" BoldFont="No"/>
							<Item Name="XSLT Keyword" Foreground="0x00FFC440" Background="0x02000000" BoldFont="No"/>
						</Items>
					</Category>
					<Category GUID="{EE1BE240-4E81-4BEB-8EEA-54322B6B1BF5}" FontName="Droid Sans Mono" FontSize="9" CharSet="0" FontIsDefault="No">
						<Items>
							<Item Name="Plain Text" Foreground="0x0000FF80" Background="0x00303030" BoldFont="No"/>
							<Item Name="Selected Text" Foreground="0x02000000" Background="0x02000000" BoldFont="No"/>
							<Item Name="Inactive Selected Text" Foreground="0x02000000" Background="0x02000000" BoldFont="No"/>
						</Items>
					</Category>
					<Category GUID="{F7B7B222-E186-48DF-A5EE-174E8129891B}" FontName="Tahoma" FontSize="8" CharSet="0" FontIsDefault="No">
						<Items/>
					</Category>
					<Category GUID="{F9D6BCE6-C669-41DB-8EE7-DD953828685B}" FontIsDefault="Yes">
						<Items>
							<Item Name="Plain Text" Foreground="0x02000000" Background="0x02000000" BoldFont="No"/>
							<Item Name="Selected Text" Foreground="0x02000000" Background="0x02000000" BoldFont="No"/>
						</Items>
					</Category>
					<Category GUID="{FA937F7B-C0D2-46B8-9F10-A7A92642B384}" FontIsDefault="Yes">
						<Items>
							<Item Name="Artboard Background" Foreground="0x02000000" Background="0x02000000" BoldFont="No"/>
						</Items>
					</Category>
					<Category GUID="{FD2219AF-EBF8-4116-A801-3B503C48DFF0}" FontName="Tahoma" FontSize="8" CharSet="0" FontIsDefault="No">
						<Items/>
					</Category>
					<Category GUID="{FF349800-EA43-46C1-8C98-878E78F46501}" FontName="Consolas" FontSize="11" CharSet="0" FontIsDefault="No">
						<Items>
							<Item Name="Read-Only Region" Foreground="0x01000002" Background="0x00646464" BoldFont="No"/>
							<Item Name="Code Snippet Field" Foreground="0x02000000" Background="0x00004000" BoldFont="No"/>
							<Item Name="Smart Tag" Foreground="0x0000FFFF" Background="0x02000000" BoldFont="No"/>
							<Item Name="Brace Matching (Rectangle)" Foreground="0x02000000" Background="0x00949494" BoldFont="Yes"/>
							<Item Name="Brace Matching (Highlight)" Foreground="0x004080FF" Background="0x02000000" BoldFont="Yes"/>
							<Item Name="Refactoring Background" Foreground="0x01000002" Background="0x00303030" BoldFont="No"/>
							<Item Name="Code Snippet Dependent Field" Foreground="0x02000000" Background="0x02000000" BoldFont="No"/>
							<Item Name="Refactoring Current Field" Foreground="0x02000000" Background="0x00FF8080" BoldFont="No"/>
							<Item Name="Refactoring Dependent Field" Foreground="0x000000FF" Background="0x02000000" BoldFont="No"/>
							<Item Name="SQL DML Marker" Foreground="0x00FFFF00" Background="0x02000000" BoldFont="No"/>
						</Items>
					</Category>
				</Categories>
			</FontsAndColors>
		</Category>
	</Category>
</UserSettings>

**Comment by dungpa** [comment] 2015-07-24 23:12
@pchalamet Thanks for the setting file. Could you check whether the issue is fixed with the latest version https://ci.appveyor.com/project/dungpa/visualfsharppowertools/build/2.0.0-a1507242305/artifacts?

**Comment by vasily-kirichenko** [comment] 2015-07-25 06:25
Wait until someone tested it.

**Comment by pchalamet** [comment] 2015-07-25 07:13
Yes it works.
Thanks!

**Comment by vasily-kirichenko** [comment] 2015-07-25 08:22
Fixed in https://github.com/fsprojects/VisualFSharpPowerTools/pull/1058

**Closed** 2015-07-25 08:21 UTC
Labels: bug
